// Code-interpreter container files: list a container's files and download their bytes. The
// Responses API runs code in an ephemeral container (auto-created per run); files the model writes
// (PDFs, spreadsheets, charts) live there until the container expires (20 min idle). The run worker
// uses these to capture generated artifacts and persist them to our own Blob Storage.
import { aiFetch, v1Url } from './http';
import { normalizeHttpError } from './errors';

export interface AiCreds {
  baseUrl: string;
  key: string;
}

export interface ContainerFile {
  id: string;
  /** Basename derived from `path` (e.g. `report.pdf`). */
  filename?: string;
  /** Full sandbox path (e.g. `/mnt/data/report.pdf`). */
  path?: string;
  /** `assistant` = generated by the model; `user` = an uploaded input. */
  source?: string;
  bytes?: number;
}

const MIME_BY_EXT: Record<string, string> = {
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  csv: 'text/csv',
  json: 'application/json',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  webp: 'image/webp',
  txt: 'text/plain',
  md: 'text/markdown',
  zip: 'application/zip',
};

/** Best-effort mime from a filename extension (`application/octet-stream` when unknown). */
export function mimeForFilename(name: string): string {
  const ext = name.split('.').pop()?.toLowerCase() ?? '';
  return MIME_BY_EXT[ext] ?? 'application/octet-stream';
}

/** GET <base>/containers/{id}/files — list the files in a code-interpreter container. */
export async function listContainerFiles(
  creds: AiCreds,
  containerId: string,
  fetchImpl?: typeof fetch,
): Promise<ContainerFile[]> {
  const url = v1Url(creds.baseUrl, `/containers/${encodeURIComponent(containerId)}/files`);
  const res = await aiFetch({
    baseUrl: creds.baseUrl,
    key: creds.key,
    url,
    method: 'GET',
    timeoutMs: 30_000,
    fetchImpl,
  });
  if (!res.ok) throw await normalizeHttpError(res, 'code_interpreter');
  const json = (await res.json()) as {
    data?: Array<{ id?: string; path?: string; source?: string; bytes?: number }>;
  };
  return (json.data ?? [])
    .filter((f): f is { id: string; path?: string; source?: string; bytes?: number } => typeof f.id === 'string')
    .map((f) => ({
      id: f.id,
      ...(f.path ? { path: f.path, filename: f.path.split('/').pop() || f.path } : {}),
      ...(f.source ? { source: f.source } : {}),
      ...(typeof f.bytes === 'number' ? { bytes: f.bytes } : {}),
    }));
}

/** GET <base>/containers/{id}/files/{fileId}/content — download the file bytes. */
export async function getContainerFile(
  creds: AiCreds,
  containerId: string,
  fileId: string,
  fetchImpl?: typeof fetch,
): Promise<Uint8Array> {
  const url = v1Url(
    creds.baseUrl,
    `/containers/${encodeURIComponent(containerId)}/files/${encodeURIComponent(fileId)}/content`,
  );
  const res = await aiFetch({
    baseUrl: creds.baseUrl,
    key: creds.key,
    url,
    method: 'GET',
    timeoutMs: 120_000,
    fetchImpl,
  });
  if (!res.ok) throw await normalizeHttpError(res, 'code_interpreter');
  return new Uint8Array(await res.arrayBuffer());
}
