import type { Message, Thread } from '../lib/types';
import { newId } from '../lib/ids';

function iso(daysAgo: number, hour = 10): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

interface SeedThread {
  thread: Thread;
  messages: Message[];
}

function thread(partial: Partial<Thread> & { id: string; title: string; updatedAt: string }): Thread {
  return {
    pinned: false,
    archived: false,
    temporary: false,
    createdAt: partial.updatedAt,
    messageCount: 0,
    ...partial,
  };
}

function userMsg(threadId: string, content: string, createdAt: string): Message {
  return { id: newId(), threadId, role: 'user', content, status: 'complete', createdAt };
}

function botMsg(threadId: string, content: string, createdAt: string): Message {
  return {
    id: newId(),
    threadId,
    role: 'assistant',
    content,
    model: 'gpt-5.4',
    status: 'complete',
    createdAt,
  };
}

const MD_CODE = `Here's a debounce hook in TypeScript:

\`\`\`ts
import { useEffect, useState } from 'react';

export function useDebounced<T>(value: T, delay = 300): T {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const id = setTimeout(() => setDebounced(value), delay);
    return () => clearTimeout(id);
  }, [value, delay]);
  return debounced;
}
\`\`\`

It returns the latest value only after \`delay\` ms of quiet. Use it for search inputs.`;

const MD_TABLE = `Quick comparison:

| Approach | Latency | Setup |
| --- | --- | --- |
| Direct (BYO key) | Lowest | None |
| Proxy | +1 hop | Server |
| Cached | Lowest | Some |

The **direct** path is the default in Watai.`;

const MD_MATH = `The Gaussian integral is:

$$\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}$$

Inline, Euler's identity $e^{i\\pi} + 1 = 0$ ties together five constants.`;

// ---- Demo asset builders (offline-safe data URLs) ----

function svgDataUrl(label: string, c1: string, c2: string): string {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400" viewBox="0 0 640 400">` +
    `<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">` +
    `<stop offset="0" stop-color="${c1}"/><stop offset="1" stop-color="${c2}"/></linearGradient></defs>` +
    `<rect width="640" height="400" fill="url(#g)"/>` +
    `<text x="50%" y="50%" fill="#ffffff" font-family="sans-serif" font-size="34" font-weight="700" ` +
    `text-anchor="middle" dominant-baseline="middle">${label}</text></svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

function samplePdfDataUrl(title: string): string {
  const objs: string[] = [];
  objs[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objs[2] = '<< /Type /Pages /Kids [3 0 R] /Count 1 >>';
  objs[3] =
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 320 160] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>';
  const stream = `BT /F1 22 Tf 28 96 Td (${title}) Tj 0 -32 Td /F1 13 Tf (Generated by Watai for preview.) Tj ET`;
  objs[4] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;
  objs[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (let i = 1; i <= 5; i++) {
    offsets[i] = pdf.length;
    pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`;
  }
  const xrefStart = pdf.length;
  pdf += 'xref\n0 6\n0000000000 65535 f \n';
  for (let i = 1; i <= 5; i++) pdf += String(offsets[i]).padStart(10, '0') + ' 00000 n \n';
  pdf += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return `data:application/pdf;base64,${btoa(pdf)}`;
}

function toneWavDataUrl(freq = 440, ms = 260): string {
  const rate = 8000;
  const n = Math.floor((rate * ms) / 1000);
  const buf = new Uint8Array(44 + n);
  const view = new DataView(buf.buffer);
  const put = (o: number, s: string) => {
    for (let i = 0; i < s.length; i++) view.setUint8(o + i, s.charCodeAt(i));
  };
  put(0, 'RIFF');
  view.setUint32(4, 36 + n, true);
  put(8, 'WAVE');
  put(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, rate, true);
  view.setUint32(28, rate, true);
  view.setUint16(32, 1, true);
  view.setUint16(34, 8, true);
  put(36, 'data');
  view.setUint32(40, n, true);
  for (let i = 0; i < n; i++) {
    const env = Math.min(1, Math.min(i, n - i) / (rate * 0.02));
    const s = Math.sin((2 * Math.PI * freq * i) / rate) * env;
    view.setUint8(44 + i, Math.round(128 + s * 100));
  }
  let bin = '';
  for (let i = 0; i < buf.length; i++) bin += String.fromCharCode(buf[i]);
  return `data:audio/wav;base64,${btoa(bin)}`;
}

function csvDataUrl(): string {
  const csv = 'name,role,latency_ms\nDirect,BYO key,120\nProxy,server,210\nCached,memory,90\n';
  return `data:text/csv;base64,${btoa(csv)}`;
}

export function buildSeed(): SeedThread[] {
  const t1 = 'seed-design-tokens';
  const t2 = 'seed-debounce';
  const t3 = 'seed-math';
  const t4 = 'seed-trip';
  const t5 = 'seed-compare';
  const t6 = 'seed-archived';
  const t7 = 'seed-showcase';
  const t8 = 'seed-attachments';

  const showcaseImg = svgDataUrl('Inline markdown image', '#6d8bff', '#9b5cff');
  const refA = svgDataUrl('Reference A', '#22c55e', '#0ea5e9');
  const refB = svgDataUrl('Reference B', '#f97316', '#ef4444');
  const genImg = svgDataUrl('Generated render', '#0ea5e9', '#6d28d9');

  const mdShowcase =
    `# Formatting showcase\n\n` +
    `This message exercises **every** renderer Watai supports — handy for reviewing chat fidelity.\n\n` +
    `## Text & emphasis\n` +
    `Use **bold**, *italic*, ***both***, ~~strikethrough~~ and \`inline code\`. ` +
    `Links open safely in a new tab: [openai.com](https://openai.com).\n\n` +
    `> Blockquotes are great for asides and callouts.\n\n` +
    `## Lists\n` +
    `- Fruits\n  - Apple\n  - Banana\n- Vegetables\n  - Carrot\n\n` +
    `1. First\n2. Second\n3. Third\n\n` +
    `Task list:\n\n` +
    `- [x] Render markdown\n- [x] Highlight code\n- [ ] Ship to production\n\n` +
    `## Table\n` +
    `| Feature | Status | Notes |\n| --- | :---: | --- |\n` +
    `| Streaming | yes | token-by-token |\n| Code copy | yes | per block |\n| Math | yes | KaTeX |\n\n` +
    `## Code\n` +
    `\`\`\`ts\ntype Result<T> = { ok: true; value: T } | { ok: false; error: string };\n\n` +
    `export function parse(json: string): Result<unknown> {\n` +
    `  try { return { ok: true, value: JSON.parse(json) }; }\n` +
    `  catch (e) { return { ok: false, error: String(e) }; }\n}\n\`\`\`\n\n` +
    `\`\`\`python\ndef fib(n: int):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\`\`\`\n\n` +
    `\`\`\`bash\nnpm install && npm run build\n\`\`\`\n\n` +
    `\`\`\`json\n{ "model": "gpt-5.4", "stream": true }\n\`\`\`\n\n` +
    `## Math\n` +
    `Inline: the area of a circle is $A = \\pi r^2$.\n\n` +
    `$$\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}$$\n\n` +
    `## Image\n` +
    `![Gradient sample](${showcaseImg})\n\n` +
    `## Footnote\n` +
    `Watai talks directly to your endpoint.[^1]\n\n` +
    `[^1]: No proxy server sits in between — your key stays on device.\n\n` +
    `---\nThat's the full set.`;

  return [
    {
      thread: thread({
        id: t7,
        title: 'Formatting showcase',
        updatedAt: iso(0, 8),
        pinned: true,
        model: 'gpt-5.4',
        lastMessagePreview: 'Every renderer Watai supports…',
        messageCount: 2,
      }),
      messages: [
        userMsg(t7, 'Show me everything the chat can render.', iso(0, 8)),
        botMsg(t7, mdShowcase, iso(0, 8)),
      ],
    },
    {
      thread: thread({
        id: t8,
        title: 'Attachments & previews',
        updatedAt: iso(0, 7),
        model: 'gpt-5.4',
        lastMessagePreview: 'Images, PDF, SVG, audio and files…',
        messageCount: 2,
      }),
      messages: [
        {
          ...userMsg(
            t8,
            'Here are two reference images, a spec PDF, a CSV and a voice note — can you summarise?',
            iso(0, 7),
          ),
          attachments: [
            { id: newId(), kind: 'image', mime: 'image/svg+xml', bytes: refA.length, name: 'reference-a.svg', blobPath: refA, width: 640, height: 400 },
            { id: newId(), kind: 'image', mime: 'image/svg+xml', bytes: refB.length, name: 'reference-b.svg', blobPath: refB, width: 640, height: 400 },
            { id: newId(), kind: 'file', mime: 'application/pdf', bytes: 800, name: 'spec.pdf', blobPath: samplePdfDataUrl('Watai Spec') },
            { id: newId(), kind: 'file', mime: 'text/csv', bytes: 80, name: 'latency.csv', blobPath: csvDataUrl() },
            { id: newId(), kind: 'audio', mime: 'audio/wav', bytes: 2100, name: 'voice-note.wav', blobPath: toneWavDataUrl() },
          ],
        },
        {
          ...botMsg(
            t8,
            'Here is a quick summary plus a generated concept image:\n\n' +
              '- **reference-a.svg** and **reference-b.svg** show two gradient directions.\n' +
              '- **spec.pdf** describes the direct, bring-your-own-key data path.\n' +
              '- **latency.csv** lists Direct (120 ms), Proxy (210 ms) and Cached (90 ms).\n\n' +
              'A rendered concept based on these is below.',
            iso(0, 7),
          ),
          images: [
            { id: newId(), prompt: 'Concept render blending both references', size: '1024x1024', outputFormat: 'png', createdAt: iso(0, 7), blobPath: genImg },
          ],
        },
      ],
    },
    {
      thread: thread({
        id: t1,
        title: 'Design token naming',
        updatedAt: iso(0, 9),
        pinned: true,
        model: 'gpt-5.4',
        lastMessagePreview: 'Use semantic aliases over raw primitives…',
        messageCount: 2,
      }),
      messages: [
        userMsg(t1, 'How should I name design tokens for a theme-able app?', iso(0, 9)),
        botMsg(
          t1,
          'Use a **two-layer** system:\n\n1. **Primitives** — raw scales like `gray-500`, `blue-500`. Never used directly.\n2. **Semantic tokens** — role-based aliases like `--color-bg`, `--color-text-primary`.\n\nComponents reference only the semantic layer, so swapping themes never touches component code.',
          iso(0, 9),
        ),
      ],
    },
    {
      thread: thread({
        id: t2,
        title: 'Debounce hook',
        updatedAt: iso(0, 14),
        model: 'gpt-5.4',
        lastMessagePreview: "Here's a debounce hook in TypeScript…",
        messageCount: 2,
      }),
      messages: [
        userMsg(t2, 'Write a React useDebounced hook in TypeScript.', iso(0, 14)),
        botMsg(t2, MD_CODE, iso(0, 14)),
      ],
    },
    {
      thread: thread({
        id: t3,
        title: 'Gaussian integral',
        updatedAt: iso(1, 11),
        model: 'gpt-5.4',
        lastMessagePreview: 'The Gaussian integral is…',
        messageCount: 2,
      }),
      messages: [
        userMsg(t3, 'Show me the Gaussian integral and Euler identity.', iso(1, 11)),
        botMsg(t3, MD_MATH, iso(1, 11)),
      ],
    },
    {
      thread: thread({
        id: t5,
        title: 'Direct vs proxy',
        updatedAt: iso(3, 16),
        model: 'gpt-5.4',
        lastMessagePreview: 'Quick comparison…',
        messageCount: 2,
      }),
      messages: [
        userMsg(t5, 'Compare direct vs proxy for calling the AI endpoint.', iso(3, 16)),
        botMsg(t5, MD_TABLE, iso(3, 16)),
      ],
    },
    {
      thread: thread({
        id: t4,
        title: 'Trip to Kyoto',
        updatedAt: iso(9, 18),
        model: 'gpt-5.4',
        lastMessagePreview: 'Three days in Kyoto…',
        messageCount: 2,
      }),
      messages: [
        userMsg(t4, 'Plan 3 days in Kyoto for first-timers.', iso(9, 18)),
        botMsg(
          t4,
          '### Day 1 — East\n- Kiyomizu-dera at opening\n- Walk Sannenzaka & Ninenzaka\n- Gion in the evening\n\n### Day 2 — Arashiyama\n- Bamboo grove early\n- Tenryu-ji garden\n- Monkey park\n\n### Day 3 — North\n- Kinkaku-ji (Golden Pavilion)\n- Ryoan-ji rock garden\n- Nishiki Market for lunch',
          iso(9, 18),
        ),
      ],
    },
    {
      thread: thread({
        id: t6,
        title: 'Old notes (archived)',
        updatedAt: iso(40, 12),
        archived: true,
        model: 'gpt-5.4',
        lastMessagePreview: 'Archived conversation…',
        messageCount: 1,
      }),
      messages: [userMsg(t6, 'Remind me to revisit this later.', iso(40, 12))],
    },
  ];
}
